cc_library(
  name = "os",
  hdrs = [
  ],
  srcs = [
  ],
  deps = [
    "//base:base",
    "//external:glog",
    "//io:io",
  ],
  visibility = ["//visibility:public"]
)

cc_test(
  name = "os_test",
  timeout = "short",
  srcs = [
  ],
  deps = [
    "//external:gtest",
    "//test:test_main",
    ":os",
  ],
)