cc_library(
  name = "test_main",
  linkstatic = 1,
  srcs = ["test_main.cc"],
  deps = [
    "//external:glog",
    "//external:gmock",
    "//external:gtest",
  ],
  visibility = ["//visibility:public"],
)